name: Deploy to QA

on:
  workflow_dispatch:
  repository_dispatch:
    types: [apply_terraform_qa] # env specific dispatch event name

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/qa

    env:
      # agent access
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TF_AGENT }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF_AGENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan & Apply
        run: |
          terraform plan -var-file=qa.tfvars -out=plan.tfplan
          terraform apply -auto-approve "plan.tfplan"
